"""Generate the revamped erp_cache_visualization.ipynb notebook."""
import json
from pathlib import Path


def md(lines: list[str]) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": lines}


def code(lines: list[str]) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "source": lines,
        "outputs": [],
        "execution_count": None,
    }


cells: list[dict] = []

# ═══════════════════════════════════════════════════════════════════════════════
# Cell: Title
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "# Radiance-Field ERP — Cache Visualisation\n",
    "\n",
    "Loads pre-computed `.npy` caches from `data/processed/` and produces\n",
    "publication-quality figures characterising the 8-channel radiance-field\n",
    "ERP representation.\n",
    "\n",
    "**No PLY files or GPU required.** All plots read from the ERP cache.\n",
    "\n",
    "| # | Section | Visualisation |\n",
    "|---|---------|---------------|\n",
    "| 1 | Shell Strip | All 8 density shells individually |\n",
    "| 2 | MIP & Depth | Max-intensity projection and depth map |\n",
    "| 3 | Radial Depth Profile | Density vs shell at 4 azimuths |\n",
    "| 4 | Polar Density | Azimuth-averaged radial density |\n",
    "| 5 | Onion Cross-Section | Meridian slices at 4 azimuths |\n",
    "| 6 | Per-Shell Statistics | Violin plots and box plots |\n",
    "| 7 | Inter-Shell Correlation | Pearson correlation heatmap |\n",
    "| 8 | Radial Signatures | Cross-class mean shell profiles |\n",
    "| 9 | Latitude Density + SWHDC | Latitude-resolved density with SWHDC weights |\n",
    "| 10 | Feature Embedding | PCA + t-SNE of shell features |\n",
    "| 11 | Class Mean Montage | Per-pixel average density per class |\n",
    "| 12 | Sparsity & Energy | Shell sparsity and energy distribution |",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Imports
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(["---\n", "## Imports and paths"]))

cells.append(code([
    "import sys\n",
    "import warnings\n",
    "from pathlib import Path\n",
    "\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.gridspec as gridspec\n",
    "import matplotlib.colors as mcolors\n",
    "from matplotlib.ticker import MaxNLocator\n",
    "from scipy.ndimage import gaussian_filter\n",
    "from scipy.stats import pearsonr\n",
    "import seaborn as sns\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "PROJECT_ROOT = Path('..').resolve()\n",
    "sys.path.insert(0, str(PROJECT_ROOT))\n",
    "\n",
    "from src.preprocessing.dataset import MODELNET10_CATEGORIES\n",
    "\n",
    "plt.rcParams.update({\n",
    "    'figure.dpi': 150,\n",
    "    'savefig.dpi': 300,\n",
    "    'font.family': 'serif',\n",
    "    'font.serif': ['Times New Roman', 'DejaVu Serif'],\n",
    "    'font.size': 11,\n",
    "    'axes.titlesize': 12,\n",
    "    'axes.titleweight': 'normal',\n",
    "    'axes.labelsize': 11,\n",
    "    'xtick.labelsize': 9,\n",
    "    'ytick.labelsize': 9,\n",
    "    'legend.fontsize': 9,\n",
    "    'figure.facecolor': 'white',\n",
    "    'axes.facecolor': 'white',\n",
    "    'axes.spines.top': False,\n",
    "    'axes.spines.right': False,\n",
    "    'mathtext.fontset': 'cm',\n",
    "})\n",
    "\n",
    "FIG_DIR = PROJECT_ROOT / 'experiments' / 'figures' / 'erp_viz'\n",
    "FIG_DIR.mkdir(parents=True, exist_ok=True)\n",
    "print(f'Figures \\u2192 {FIG_DIR}')",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Config
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(["---\n", "## Configuration — point to your cache"]))

cells.append(code([
    "CACHE_CANDIDATES = [\n",
    "    PROJECT_ROOT / 'data' / 'processed' / 'modelnet10' / 'radiance_field',\n",
    "    PROJECT_ROOT / 'data' / 'processed' / 'modelnet40' / 'radiance_field',\n",
    "]\n",
    "\n",
    "CACHE_ROOT = next((c for c in CACHE_CANDIDATES if c.exists()), None)\n",
    "if CACHE_ROOT is None:\n",
    "    raise FileNotFoundError(\n",
    "        'No ERP cache found.  Run the preprocessing script first.'\n",
    "    )\n",
    "\n",
    "param_dirs = [d for d in sorted(CACHE_ROOT.iterdir()) if d.is_dir()]\n",
    "if not param_dirs:\n",
    "    raise FileNotFoundError(f'No params subdirectory found under {CACHE_ROOT}')\n",
    "PARAM_DIR = param_dirs[0]\n",
    "print(f'Cache root    : {CACHE_ROOT.name}')\n",
    "print(f'Cache params  : {PARAM_DIR.name}')\n",
    "\n",
    "# Detect N_SHELLS from the params dir name (ns<N>_...)\n",
    "import re as _re\n",
    "_ns_match = _re.search(r'ns(\\d+)', PARAM_DIR.name)\n",
    "N_SHELLS = int(_ns_match.group(1)) if _ns_match else 8\n",
    "print(f'N_SHELLS      : {N_SHELLS}')\n",
    "\n",
    "# Discover cached classes\n",
    "ALL_CLASSES = sorted([d.name for d in PARAM_DIR.iterdir() if d.is_dir()])\n",
    "\n",
    "# Helpers\n",
    "def list_npys(category: str, split: str = 'train') -> list[Path]:\n",
    "    d = PARAM_DIR / category / split\n",
    "    return sorted(d.glob('*.npy')) if d.exists() else []\n",
    "\n",
    "def load_erp(path: Path) -> np.ndarray:\n",
    "    return np.load(path).astype(np.float32)\n",
    "\n",
    "def normalise(arr: np.ndarray) -> np.ndarray:\n",
    "    lo, hi = arr.min(), arr.max()\n",
    "    return (arr - lo) / (hi - lo + 1e-12)\n",
    "\n",
    "def load_class_erps(cls: str, split: str = 'train', max_n: int | None = None) -> list[np.ndarray]:\n",
    "    paths = list_npys(cls, split)\n",
    "    if max_n is not None:\n",
    "        paths = paths[:max_n]\n",
    "    return [load_erp(p) for p in paths]\n",
    "\n",
    "# Consistent class colours\n",
    "_tab10 = plt.cm.tab10.colors\n",
    "CLASS_COLORS = {cls: _tab10[i % 10] for i, cls in enumerate(ALL_CLASSES)}\n",
    "STAT_CLASSES = [cls for cls in ALL_CLASSES if len(list_npys(cls, 'train')) >= 20]\n",
    "SHELL_COLORS = plt.cm.plasma(np.linspace(0.15, 0.9, N_SHELLS))\n",
    "\n",
    "# Pick a reference sample\n",
    "FOCUS_CLASS = 'desk' if 'desk' in ALL_CLASSES else ALL_CLASSES[0]\n",
    "sample_paths = list_npys(FOCUS_CLASS, 'train')\n",
    "if not sample_paths:\n",
    "    FOCUS_CLASS = next((c for c in ALL_CLASSES if list_npys(c)), None)\n",
    "    sample_paths = list_npys(FOCUS_CLASS, 'train')\n",
    "if not sample_paths:\n",
    "    raise FileNotFoundError('No cached .npy files found.')\n",
    "\n",
    "REF_PATH = sample_paths[0]\n",
    "erp = load_erp(REF_PATH)\n",
    "H, W = erp.shape[1], erp.shape[2]\n",
    "\n",
    "# Degree-based tick helpers (reused across sections)\n",
    "az_ticks = np.linspace(0, W, 5)\n",
    "az_labels = ['0\\u00b0', '90\\u00b0', '180\\u00b0', '270\\u00b0', '360\\u00b0']\n",
    "el_ticks = np.linspace(0, H, 3)\n",
    "el_labels = ['+90\\u00b0', '0\\u00b0', '\\u221290\\u00b0']\n",
    "\n",
    "print(f'Reference class  : {FOCUS_CLASS}')\n",
    "print(f'Sample file      : {REF_PATH.name}')\n",
    "print(f'ERP shape        : {erp.shape}   (N_shells={erp.shape[0]}, H={H}, W={W})')\n",
    "print(f'Value range      : [{erp.min():.4f}, {erp.max():.4f}]')\n",
    "print(f'Available classes : {ALL_CLASSES}')\n",
    "print(f'Stat classes     : {STAT_CLASSES}')",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Pre-computation
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(["---\n", "## Pre-compute per-class statistics"]))

cells.append(code([
    "print('Pre-computing per-class statistics ...')\n",
    "\n",
    "class_shell_profiles = {}   # cls -> (N, 8)\n",
    "class_lat_profiles   = {}   # cls -> (N, H)\n",
    "class_features       = {}   # cls -> (N, 48)\n",
    "class_sparsity       = {}   # cls -> (N, 8)\n",
    "class_energy_frac    = {}   # cls -> (N, 8)\n",
    "\n",
    "for cls in ALL_CLASSES:\n",
    "    erps = load_class_erps(cls, 'train', max_n=80)\n",
    "    if not erps:\n",
    "        continue\n",
    "\n",
    "    shell_profiles, lat_profiles, features, sparsity, energy_frac = [], [], [], [], []\n",
    "\n",
    "    for e in erps:\n",
    "        shell_profiles.append(e.mean(axis=(1, 2)))\n",
    "        lat_profiles.append(e.mean(axis=(0, 2)))\n",
    "        sparsity.append(np.array([(e[s] < 1e-6).mean() for s in range(N_SHELLS)]))\n",
    "        shell_sums = e.sum(axis=(1, 2))\n",
    "        total = shell_sums.sum()\n",
    "        energy_frac.append(shell_sums / (total + 1e-12))\n",
    "        feat = []\n",
    "        for s in range(N_SHELLS):\n",
    "            v = e[s].ravel()\n",
    "            feat.extend([v.mean(), v.std(),\n",
    "                         np.percentile(v, 25), np.percentile(v, 50),\n",
    "                         np.percentile(v, 75), (v < 1e-6).mean()])\n",
    "        features.append(feat)\n",
    "\n",
    "    class_shell_profiles[cls] = np.array(shell_profiles)\n",
    "    class_lat_profiles[cls]   = np.array(lat_profiles)\n",
    "    class_features[cls]       = np.array(features)\n",
    "    class_sparsity[cls]       = np.array(sparsity)\n",
    "    class_energy_frac[cls]    = np.array(energy_frac)\n",
    "    print(f'  {cls:15s}: {len(erps):4d} samples')\n",
    "\n",
    "print(f'\\nSTAT_CLASSES ({len(STAT_CLASSES)}): {STAT_CLASSES}')",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Section 1 — Shell Strip
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "---\n",
    "## Section 1 — Shell Strip: all 8 density maps\n",
    "\n",
    "Each panel shows one ERP channel (one concentric shell). Shell 1 is the\n",
    "innermost (smallest radius) and Shell 8 is the outermost.",
]))

cells.append(code([
    "vmin, vmax = 0, erp.max()\n",
    "\n",
    "fig, axes = plt.subplots(2, 4, figsize=(18, 6),\n",
    "                          gridspec_kw={'hspace': 0.45, 'wspace': 0.25})\n",
    "\n",
    "panel_labels = 'abcdefgh'\n",
    "\n",
    "for s, ax in enumerate(axes.flat):\n",
    "    d = gaussian_filter(erp[s], sigma=0.8)\n",
    "    im = ax.imshow(d, cmap='inferno', aspect='auto', interpolation='bilinear',\n",
    "                   vmin=vmin, vmax=vmax)\n",
    "    ax.set_title(f'Shell {s + 1}', fontsize=10, pad=3)\n",
    "    ax.set_xticks(az_ticks)\n",
    "    ax.set_xticklabels(az_labels, fontsize=7)\n",
    "    ax.set_yticks(el_ticks)\n",
    "    ax.set_yticklabels(el_labels, fontsize=7)\n",
    "    ax.set_xlabel('Azimuth', fontsize=8)\n",
    "    ax.set_ylabel('Elevation', fontsize=8)\n",
    "    ax.text(-0.08, 1.05, f'({panel_labels[s]})', transform=ax.transAxes,\n",
    "            fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "# Shared colorbar\n",
    "fig.subplots_adjust(right=0.92)\n",
    "cbar_ax = fig.add_axes([0.94, 0.15, 0.015, 0.7])\n",
    "fig.colorbar(im, cax=cbar_ax, label='Density')\n",
    "\n",
    "fig.suptitle(\n",
    "    f'Radiance-Field ERP — 8 density shells | class: {FOCUS_CLASS}',\n",
    "    fontsize=13, y=1.01,\n",
    ")\n",
    "fig.savefig(FIG_DIR / '1_shell_strip.pdf', bbox_inches='tight')\n",
    "plt.show()",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Section 2 — MIP & Depth
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "---\n",
    "## Section 2 — Max-Intensity Projection (MIP) and Depth Map\n",
    "\n",
    "**MIP** collapses the shell axis by taking the maximum density across all shells.\n",
    "**Depth map** shows the first shell index exceeding a density threshold.",
]))

cells.append(code([
    "mip = erp.max(axis=0)\n",
    "mean_proj = erp.mean(axis=0)\n",
    "\n",
    "threshold = erp.max() * 0.15\n",
    "above = erp > threshold\n",
    "depth_map = np.argmax(above, axis=0).astype(float)\n",
    "depth_map[~above.any(axis=0)] = np.nan\n",
    "\n",
    "fig, axes = plt.subplots(1, 3, figsize=(16, 4.5),\n",
    "                          gridspec_kw={'wspace': 0.35})\n",
    "\n",
    "for ax in axes:\n",
    "    ax.set_xticks(az_ticks); ax.set_xticklabels(az_labels, fontsize=7)\n",
    "    ax.set_yticks(el_ticks); ax.set_yticklabels(el_labels, fontsize=7)\n",
    "    ax.set_xlabel('Azimuth', fontsize=8)\n",
    "    ax.set_ylabel('Elevation', fontsize=8)\n",
    "\n",
    "im0 = axes[0].imshow(gaussian_filter(mip, 0.8), cmap='hot', aspect='auto')\n",
    "axes[0].set_title('Max-Intensity Projection', pad=5)\n",
    "plt.colorbar(im0, ax=axes[0], fraction=0.046, pad=0.02, label='Max density')\n",
    "axes[0].text(-0.08, 1.05, '(a)', transform=axes[0].transAxes,\n",
    "             fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "im1 = axes[1].imshow(gaussian_filter(mean_proj, 0.8), cmap='magma', aspect='auto')\n",
    "axes[1].set_title('Mean Projection', pad=5)\n",
    "plt.colorbar(im1, ax=axes[1], fraction=0.046, pad=0.02, label='Mean density')\n",
    "axes[1].text(-0.08, 1.05, '(b)', transform=axes[1].transAxes,\n",
    "             fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "cmap_depth = plt.cm.viridis_r.copy()\n",
    "cmap_depth.set_bad('black', alpha=1.0)\n",
    "im2 = axes[2].imshow(depth_map, cmap=cmap_depth, aspect='auto',\n",
    "                     vmin=0, vmax=N_SHELLS - 1)\n",
    "axes[2].set_title(f'Depth Map (threshold={threshold:.2f})', pad=5)\n",
    "cbar2 = plt.colorbar(im2, ax=axes[2], fraction=0.046, pad=0.02)\n",
    "cbar2.set_label('Shell index')\n",
    "cbar2.set_ticks(range(N_SHELLS))\n",
    "cbar2.set_ticklabels([f'S{i+1}' for i in range(N_SHELLS)])\n",
    "axes[2].text(-0.08, 1.05, '(c)', transform=axes[2].transAxes,\n",
    "             fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "fig.suptitle(f'MIP, Mean Projection, and Depth Map | {FOCUS_CLASS}', fontsize=13, y=1.02)\n",
    "fig.savefig(FIG_DIR / '2_mip_depth.pdf', bbox_inches='tight')\n",
    "plt.show()\n",
    "print(f'Depth coverage: {(~np.isnan(depth_map)).mean()*100:.1f}% of pixels above threshold')",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Section 3 — Radial Depth Profile
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "---\n",
    "## Section 3 — Radial Depth Profile\n",
    "\n",
    "For a fixed azimuth column, density vs shell index as a 2-D heatmap —\n",
    "a side-view cross-section of the radial density field.",
]))

cells.append(code([
    "azimuths = [W // 4, W // 2, 3 * W // 4, 0]\n",
    "az_plot_labels = ['90\\u00b0', '180\\u00b0 (back)', '270\\u00b0', '0\\u00b0 (front)']\n",
    "\n",
    "fig, axes = plt.subplots(1, 4, figsize=(18, 4.5),\n",
    "                          gridspec_kw={'wspace': 0.35})\n",
    "\n",
    "for k, (ax, col, label) in enumerate(zip(axes, azimuths, az_plot_labels)):\n",
    "    profile = erp[:, :, col]\n",
    "    profile_smooth = gaussian_filter(profile.astype(np.float64), sigma=0.6)\n",
    "    im = ax.imshow(\n",
    "        profile_smooth.T, cmap='plasma', aspect='auto',\n",
    "        extent=[0.5, N_SHELLS + 0.5, -90, 90], origin='upper',\n",
    "    )\n",
    "    ax.set_title(f'Azimuth {label}', fontsize=10, pad=5)\n",
    "    ax.set_xlabel('Shell index (inner \\u2192 outer)', fontsize=9)\n",
    "    ax.set_ylabel('Elevation (\\u00b0)', fontsize=9)\n",
    "    ax.set_xticks(range(1, N_SHELLS + 1))\n",
    "    ax.tick_params(labelsize=7)\n",
    "    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.02, label='Density')\n",
    "    ax.text(-0.08, 1.05, f'({\"abcd\"[k]})', transform=ax.transAxes,\n",
    "            fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "fig.suptitle(f'Radial Depth Profile | {FOCUS_CLASS}', fontsize=13, y=1.04)\n",
    "fig.savefig(FIG_DIR / '3_radial_depth_profile.pdf', bbox_inches='tight')\n",
    "plt.show()",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Section 4 — Polar Density
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "---\n",
    "## Section 4 — Polar Plot: azimuth-averaged radial density\n",
    "\n",
    "Average density over all elevations for each azimuth column, plotted on\n",
    "polar coordinates (radius = shell index, angle = azimuth).",
]))

cells.append(code([
    "az_mean = erp.mean(axis=1)    # (N_shells, W)\n",
    "theta = np.linspace(0, 2 * np.pi, W, endpoint=False)\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(12, 5),\n",
    "                          subplot_kw={'projection': 'polar'},\n",
    "                          gridspec_kw={'wspace': 0.4})\n",
    "\n",
    "cmap_shells = plt.cm.viridis\n",
    "norm_shells = mcolors.Normalize(vmin=1, vmax=N_SHELLS)\n",
    "\n",
    "for s in range(N_SHELLS):\n",
    "    rho = normalise(az_mean[s]) + s + 1\n",
    "    axes[0].plot(theta, rho,\n",
    "                 color=cmap_shells(norm_shells(s + 1)),\n",
    "                 linewidth=1.5, alpha=0.85,\n",
    "                 label=f'S{s+1}')\n",
    "\n",
    "axes[0].set_title('Azimuthal density\\n(shells offset by index)', pad=15, fontsize=10)\n",
    "axes[0].legend(loc='lower right', bbox_to_anchor=(1.25, -0.08),\n",
    "               fontsize=7, ncol=2)\n",
    "\n",
    "# Polar heatmap\n",
    "dtheta = 2 * np.pi / W\n",
    "for s in range(N_SHELLS):\n",
    "    rho_inner = s + 1\n",
    "    rho_outer = s + 2\n",
    "    vals = normalise(az_mean[s])\n",
    "    for i in range(W):\n",
    "        color = cmap_shells(vals[i])\n",
    "        angles = [theta[i], theta[i] + dtheta]\n",
    "        axes[1].fill_between(angles, rho_inner, rho_outer,\n",
    "                             color=color, alpha=0.9, linewidth=0)\n",
    "\n",
    "axes[1].set_yticks(range(1, N_SHELLS + 2))\n",
    "axes[1].set_yticklabels([f'S{s}' for s in range(1, N_SHELLS + 2)], fontsize=6)\n",
    "axes[1].set_title('Polar shell heatmap\\n(radius = shell, colour = density)', pad=15, fontsize=10)\n",
    "\n",
    "fig.suptitle(f'Polar Radial Density | {FOCUS_CLASS}', fontsize=13, y=1.02)\n",
    "fig.savefig(FIG_DIR / '4_polar_density.pdf', bbox_inches='tight')\n",
    "plt.show()",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Section 5 — Onion Cross-Section
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "---\n",
    "## Section 5 — Onion Cross-Section (meridian slice)\n",
    "\n",
    "Slice the ERP at a fixed azimuth and show the density as concentric rings\n",
    "on a 2-D cross-section plane. Inner rings correspond to inner shells.",
]))

cells.append(code([
    "from matplotlib.patches import Wedge\n",
    "from matplotlib.collections import PatchCollection\n",
    "\n",
    "def onion_cross_section(erp_arr, az_col: int, n_elev_bins: int = 36, ax=None):\n",
    "    if ax is None:\n",
    "        _, ax = plt.subplots(subplot_kw={'projection': 'polar'})\n",
    "    bins = np.array_split(np.arange(H), n_elev_bins)\n",
    "    elev_angles = np.linspace(0, np.pi, n_elev_bins + 1)\n",
    "    for s in range(N_SHELLS):\n",
    "        r_inner = s / N_SHELLS\n",
    "        r_outer = (s + 1) / N_SHELLS\n",
    "        for e, (idx_group, a0, a1) in enumerate(\n",
    "                zip(bins, elev_angles[:-1], elev_angles[1:])):\n",
    "            val = normalise(erp_arr[s, idx_group, az_col]).mean()\n",
    "            color = plt.cm.inferno(val)\n",
    "            for theta_offset in (0, np.pi):\n",
    "                ax.fill_between(\n",
    "                    [a0 + theta_offset, a1 + theta_offset],\n",
    "                    r_inner, r_outer, color=color, linewidth=0)\n",
    "    ax.set_yticks([(s + 0.5) / N_SHELLS for s in range(N_SHELLS)])\n",
    "    ax.set_yticklabels([f'S{s+1}' for s in range(N_SHELLS)], fontsize=6)\n",
    "    ax.set_xticks(np.linspace(0, 2 * np.pi, 5)[:-1])\n",
    "    ax.set_xticklabels(['0\\u00b0', '90\\u00b0', '180\\u00b0', '270\\u00b0'], fontsize=7)\n",
    "    return ax\n",
    "\n",
    "fig = plt.figure(figsize=(16, 5))\n",
    "az_cols  = [0, W // 4, W // 2, 3 * W // 4]\n",
    "az_names = ['0\\u00b0 (front)', '90\\u00b0', '180\\u00b0 (back)', '270\\u00b0']\n",
    "\n",
    "for k, (col, name) in enumerate(zip(az_cols, az_names)):\n",
    "    ax = fig.add_subplot(1, 4, k + 1, projection='polar')\n",
    "    onion_cross_section(erp, az_col=col, ax=ax)\n",
    "    ax.set_title(f'Azimuth {name}', fontsize=9, pad=10)\n",
    "\n",
    "sm = plt.cm.ScalarMappable(cmap='inferno', norm=mcolors.Normalize(0, 1))\n",
    "sm.set_array([])\n",
    "cbar = fig.colorbar(sm, ax=fig.axes, fraction=0.02, pad=0.06)\n",
    "cbar.set_label('Normalised density', fontsize=9)\n",
    "\n",
    "fig.suptitle(\n",
    "    f'Onion Cross-Section — meridian slices | {FOCUS_CLASS}',\n",
    "    fontsize=13, y=1.04,\n",
    ")\n",
    "fig.savefig(FIG_DIR / '5_onion_cross_section.pdf', bbox_inches='tight')\n",
    "plt.show()",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Section 6 — Per-Shell Statistics
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "---\n",
    "## Section 6 — Per-Shell Statistics: violin and box plots\n",
    "\n",
    "Distribution of raw density values at each shell.",
]))

cells.append(code([
    "fig, axes = plt.subplots(1, 2, figsize=(15, 5), gridspec_kw={'wspace': 0.35})\n",
    "\n",
    "# Left: violin plots (non-zero pixels)\n",
    "violin_data = []\n",
    "violin_labels = []\n",
    "for s in range(N_SHELLS):\n",
    "    vals = erp[s].ravel()\n",
    "    vals_pos = vals[vals > 1e-6]\n",
    "    if len(vals_pos) > 10000:\n",
    "        vals_pos = np.random.default_rng(42).choice(vals_pos, 10000, replace=False)\n",
    "    violin_data.append(vals_pos)\n",
    "    violin_labels.append(f'S{s+1}')\n",
    "\n",
    "parts = axes[0].violinplot(violin_data, positions=range(1, N_SHELLS + 1),\n",
    "                           showmeans=True, showmedians=True)\n",
    "for i, pc in enumerate(parts['bodies']):\n",
    "    pc.set_facecolor(SHELL_COLORS[i])\n",
    "    pc.set_alpha(0.7)\n",
    "parts['cmeans'].set_color('red')\n",
    "parts['cmedians'].set_color('black')\n",
    "\n",
    "axes[0].set_yscale('log')\n",
    "axes[0].set_xticks(range(1, N_SHELLS + 1))\n",
    "axes[0].set_xticklabels(violin_labels)\n",
    "axes[0].set_xlabel('Shell')\n",
    "axes[0].set_ylabel('Density (log scale)')\n",
    "axes[0].set_title('Violin plots (non-zero pixels)')\n",
    "axes[0].text(-0.08, 1.05, '(a)', transform=axes[0].transAxes,\n",
    "             fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "# Right: box plots (all pixels)\n",
    "data_bp = [erp[s].ravel() for s in range(N_SHELLS)]\n",
    "bp = axes[1].boxplot(\n",
    "    data_bp, patch_artist=True,\n",
    "    medianprops=dict(color='black', linewidth=1.5),\n",
    "    whiskerprops=dict(linewidth=1),\n",
    "    flierprops=dict(marker='.', markersize=2, alpha=0.3),\n",
    ")\n",
    "for patch, color in zip(bp['boxes'], SHELL_COLORS):\n",
    "    patch.set_facecolor(color)\n",
    "    patch.set_alpha(0.75)\n",
    "\n",
    "axes[1].set_yscale('log')\n",
    "axes[1].set_xticks(range(1, N_SHELLS + 1))\n",
    "axes[1].set_xticklabels(violin_labels)\n",
    "axes[1].set_xlabel('Shell')\n",
    "axes[1].set_ylabel('Density (log scale)')\n",
    "axes[1].set_title('Box plots (all pixels)')\n",
    "axes[1].text(-0.08, 1.05, '(b)', transform=axes[1].transAxes,\n",
    "             fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "fig.suptitle(f'Per-Shell Density Statistics | {FOCUS_CLASS}', fontsize=13, y=1.02)\n",
    "fig.savefig(FIG_DIR / '6_per_shell_stats.pdf', bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "print(f'  Shell  |  mean      |  std       |  p50       |  p99')\n",
    "print(f'  {\"\\u2500\"*55}')\n",
    "for s in range(N_SHELLS):\n",
    "    v = erp[s].ravel()\n",
    "    print(f'  S{s+1:1d}     |  {v.mean():.6f}  |  {v.std():.6f}  |  '\n",
    "          f'{np.percentile(v,50):.6f}  |  {np.percentile(v,99):.6f}')",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Section 7 — Inter-Shell Correlation
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "---\n",
    "## Section 7 — Inter-Shell Correlation Matrix\n",
    "\n",
    "Pearson correlation between flattened shell density maps. High correlation\n",
    "between adjacent shells is expected; low between inner and outer shells.",
]))

cells.append(code([
    "flat = erp.reshape(N_SHELLS, -1)\n",
    "corr = np.corrcoef(flat)  # (N_SHELLS, N_SHELLS)\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(13, 5), gridspec_kw={'wspace': 0.4})\n",
    "\n",
    "# Left: correlation matrix\n",
    "ax = axes[0]\n",
    "im = ax.imshow(corr, cmap='RdBu_r', vmin=-1, vmax=1, aspect='equal')\n",
    "for i in range(N_SHELLS):\n",
    "    for j in range(N_SHELLS):\n",
    "        ax.text(j, i, f'{corr[i,j]:.2f}', ha='center', va='center',\n",
    "                fontsize=7, color='black' if abs(corr[i,j]) < 0.7 else 'white')\n",
    "ax.set_xticks(range(N_SHELLS))\n",
    "ax.set_yticks(range(N_SHELLS))\n",
    "ax.set_xticklabels([f'S{s+1}' for s in range(N_SHELLS)], fontsize=8)\n",
    "ax.set_yticklabels([f'S{s+1}' for s in range(N_SHELLS)], fontsize=8)\n",
    "ax.set_title('Pearson Correlation Matrix')\n",
    "plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label='$r$')\n",
    "ax.text(-0.08, 1.05, '(a)', transform=ax.transAxes,\n",
    "        fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "# Right: correlation vs shell distance\n",
    "ax = axes[1]\n",
    "distances = np.arange(0, N_SHELLS)\n",
    "mean_corr_by_dist = [\n",
    "    np.mean([corr[i, j] for i in range(N_SHELLS)\n",
    "             for j in range(N_SHELLS) if abs(i - j) == d])\n",
    "    for d in distances\n",
    "]\n",
    "ax.plot(distances, mean_corr_by_dist, 'o-', color='#2c7bb6', linewidth=2, markersize=7)\n",
    "ax.axhline(0, color='gray', linestyle='--', linewidth=0.8)\n",
    "ax.fill_between(distances, mean_corr_by_dist, alpha=0.15, color='#2c7bb6')\n",
    "ax.set_xlabel('Shell distance $|i - j|$')\n",
    "ax.set_ylabel('Mean Pearson $r$')\n",
    "ax.set_title('Correlation vs Shell Distance')\n",
    "ax.set_xticks(distances)\n",
    "ax.set_ylim(-0.1, 1.05)\n",
    "ax.text(-0.08, 1.05, '(b)', transform=ax.transAxes,\n",
    "        fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "fig.suptitle(f'Inter-Shell Correlation | {FOCUS_CLASS}', fontsize=13, y=1.02)\n",
    "fig.savefig(FIG_DIR / '7_shell_correlation.pdf', bbox_inches='tight')\n",
    "plt.show()",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Section 8 — Cross-Class Radial Signatures
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "---\n",
    "## Section 8 — Cross-Class Radial Signatures\n",
    "\n",
    "Mean density per shell for each class with \\u00b11 std shaded bands.\n",
    "Shows how different 3D object classes produce distinguishable radial\n",
    "density distributions (e.g., solid vs hollow objects).",
]))

cells.append(code([
    "fig, ax = plt.subplots(figsize=(8, 5))\n",
    "\n",
    "shell_idx = np.arange(1, N_SHELLS + 1)\n",
    "\n",
    "for cls in STAT_CLASSES:\n",
    "    profiles = class_shell_profiles[cls]  # (N, 8)\n",
    "    mu = profiles.mean(axis=0)\n",
    "    sigma = profiles.std(axis=0)\n",
    "    ax.plot(shell_idx, mu, 'o-', color=CLASS_COLORS[cls], label=cls,\n",
    "            linewidth=1.8, markersize=5)\n",
    "    ax.fill_between(shell_idx, mu - sigma, mu + sigma,\n",
    "                    color=CLASS_COLORS[cls], alpha=0.15)\n",
    "\n",
    "ax.set_xlabel('Shell index (inner \\u2192 outer)')\n",
    "ax.set_ylabel('Mean density')\n",
    "ax.set_title('Cross-Class Radial Density Signatures')\n",
    "ax.set_xticks(shell_idx)\n",
    "ax.legend(frameon=True, fancybox=False, edgecolor='gray')\n",
    "ax.grid(axis='y', alpha=0.3)\n",
    "\n",
    "fig.tight_layout()\n",
    "fig.savefig(FIG_DIR / '8_radial_signatures.pdf', bbox_inches='tight')\n",
    "plt.show()",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Section 9 — Latitude Density + SWHDC
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "---\n",
    "## Section 9 — Latitude-Resolved Density with SWHDC Weights\n",
    "\n",
    "Per-class mean density as a function of latitude, overlaid with the\n",
    "SWHDC mixing weights $W_n(\\phi)$ for dilation rates 1\\u20134.\n",
    "This figure justifies the SWHDC architecture: density concentrates near\n",
    "the equator where the SWHDC weights transition between dilation rates.",
]))

cells.append(code([
    "import torch\n",
    "from src.models.blocks.swhdc import compute_swhdc_weights\n",
    "\n",
    "latitudes = np.linspace(90, -90, H)\n",
    "\n",
    "# Pick 4 representative classes\n",
    "rep_classes = [c for c in ['bed', 'chair', 'monitor', 'sofa'] if c in STAT_CLASSES]\n",
    "if len(rep_classes) < 3:\n",
    "    rep_classes = STAT_CLASSES[:4]\n",
    "\n",
    "fig, ax1 = plt.subplots(figsize=(8, 5))\n",
    "\n",
    "for cls in rep_classes:\n",
    "    lat_prof = class_lat_profiles[cls]  # (N, H)\n",
    "    mu = lat_prof.mean(axis=0)\n",
    "    ax1.plot(latitudes, mu, color=CLASS_COLORS[cls], linewidth=1.5, label=cls)\n",
    "\n",
    "ax1.set_xlabel('Latitude (degrees)')\n",
    "ax1.set_ylabel('Mean density', color='black')\n",
    "ax1.legend(loc='upper left', frameon=True, fancybox=False, edgecolor='gray')\n",
    "ax1.grid(axis='y', alpha=0.3)\n",
    "\n",
    "# SWHDC weights on secondary axis\n",
    "ax2 = ax1.twinx()\n",
    "weights = compute_swhdc_weights(H, N=4).numpy()  # (4, H)\n",
    "dilation_colors = ['#999999', '#777777', '#555555', '#333333']\n",
    "for d in range(4):\n",
    "    ax2.plot(latitudes, weights[d], linestyle='--', linewidth=1.2,\n",
    "             color=dilation_colors[d], alpha=0.7,\n",
    "             label=f'$W_{d+1}(\\\\phi)$ (rate {d+1})')\n",
    "\n",
    "ax2.set_ylabel('SWHDC weight $W_n(\\\\phi)$', color='gray')\n",
    "ax2.tick_params(axis='y', labelcolor='gray')\n",
    "ax2.legend(loc='upper right', frameon=True, fancybox=False, edgecolor='gray',\n",
    "           fontsize=8)\n",
    "ax2.spines['right'].set_visible(True)\n",
    "\n",
    "ax1.set_title('Latitude-Resolved Density with SWHDC Mixing Weights')\n",
    "fig.tight_layout()\n",
    "fig.savefig(FIG_DIR / '9_latitude_density_swhdc.pdf', bbox_inches='tight')\n",
    "plt.show()",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Section 10 — PCA + t-SNE
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "---\n",
    "## Section 10 — Feature Embedding (PCA + t-SNE)\n",
    "\n",
    "Each sample is reduced to a 48-dimensional feature vector (per-shell\n",
    "mean, std, p25, p50, p75, sparsity), then projected to 2-D.\n",
    "Shows class separability in the raw feature space before any learned model.",
]))

cells.append(code([
    "from sklearn.manifold import TSNE\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "# Build feature matrix\n",
    "X_list, y_list = [], []\n",
    "for cls in STAT_CLASSES:\n",
    "    feats = class_features[cls]  # (N, 48)\n",
    "    X_list.append(feats)\n",
    "    y_list.extend([cls] * len(feats))\n",
    "\n",
    "X = StandardScaler().fit_transform(np.vstack(X_list))\n",
    "y = np.array(y_list)\n",
    "\n",
    "pca_2d  = PCA(n_components=2).fit_transform(X)\n",
    "tsne_2d = TSNE(n_components=2, perplexity=30, random_state=42).fit_transform(X)\n",
    "\n",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))\n",
    "\n",
    "for cls in STAT_CLASSES:\n",
    "    mask = y == cls\n",
    "    ax1.scatter(pca_2d[mask, 0], pca_2d[mask, 1], s=15, alpha=0.6,\n",
    "               color=CLASS_COLORS[cls], label=cls)\n",
    "    ax2.scatter(tsne_2d[mask, 0], tsne_2d[mask, 1], s=15, alpha=0.6,\n",
    "               color=CLASS_COLORS[cls], label=cls)\n",
    "\n",
    "ax1.set_title('PCA')\n",
    "ax1.set_xlabel('PC 1')\n",
    "ax1.set_ylabel('PC 2')\n",
    "ax1.legend(fontsize=8, markerscale=2, frameon=True, fancybox=False, edgecolor='gray')\n",
    "ax1.text(-0.08, 1.05, '(a)', transform=ax1.transAxes,\n",
    "         fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "ax2.set_title('t-SNE')\n",
    "ax2.set_xlabel('t-SNE 1')\n",
    "ax2.set_ylabel('t-SNE 2')\n",
    "ax2.legend(fontsize=8, markerscale=2, frameon=True, fancybox=False, edgecolor='gray')\n",
    "ax2.text(-0.08, 1.05, '(b)', transform=ax2.transAxes,\n",
    "         fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "fig.suptitle('Shell Feature Embedding \\u2014 PCA and t-SNE', fontsize=13, y=1.02)\n",
    "fig.tight_layout()\n",
    "fig.savefig(FIG_DIR / '10_embedding_pca_tsne.pdf', bbox_inches='tight')\n",
    "plt.show()\n",
    "print(f'Total samples: {len(y)}, classes: {len(STAT_CLASSES)}')",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Section 11 — Class-Average Shell Montage
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "---\n",
    "## Section 11 — Class-Average Shell Montage\n",
    "\n",
    "Per-pixel mean density across all training samples for selected shells.\n",
    "Each row is a class; each column is a shell. Averaged patterns reveal\n",
    "structural archetypes (visual fingerprints) per class.",
]))

cells.append(code([
    "show_shells = [0, 3, 7]  # shells 1, 4, 8\n",
    "show_shell_names = ['Shell 1 (inner)', 'Shell 4 (mid)', 'Shell 8 (outer)']\n",
    "avail_classes = [cls for cls in ALL_CLASSES if cls in class_shell_profiles]\n",
    "n_cls = len(avail_classes)\n",
    "n_cols = len(show_shells)\n",
    "\n",
    "# Compute all means first to get global vmax\n",
    "mean_maps = {}  # (cls, shell_idx) -> (H, W)\n",
    "for cls in avail_classes:\n",
    "    erps_cls = load_class_erps(cls, 'train')\n",
    "    stack = np.array(erps_cls)  # (N, 8, H, W)\n",
    "    for si in show_shells:\n",
    "        mean_maps[(cls, si)] = gaussian_filter(stack[:, si].mean(axis=0), sigma=0.8)\n",
    "\n",
    "global_vmax = max(v.max() for v in mean_maps.values())\n",
    "\n",
    "fig, axes = plt.subplots(n_cls, n_cols, figsize=(4.5 * n_cols, 2.2 * n_cls),\n",
    "                          gridspec_kw={'hspace': 0.4, 'wspace': 0.15})\n",
    "if n_cls == 1:\n",
    "    axes = axes[np.newaxis, :]\n",
    "\n",
    "for r, cls in enumerate(avail_classes):\n",
    "    n_samples = len(list_npys(cls, 'train'))\n",
    "    for c, si in enumerate(show_shells):\n",
    "        ax = axes[r, c]\n",
    "        im = ax.imshow(mean_maps[(cls, si)], cmap='inferno', aspect='auto',\n",
    "                       vmin=0, vmax=global_vmax, interpolation='bilinear')\n",
    "        if c == 0:\n",
    "            ax.set_ylabel(f'{cls}\\n(n={n_samples})', fontsize=9, rotation=0,\n",
    "                          labelpad=60, ha='right', va='center')\n",
    "        if r == 0:\n",
    "            ax.set_title(show_shell_names[c], fontsize=10)\n",
    "        ax.set_xticks([])\n",
    "        ax.set_yticks([])\n",
    "\n",
    "fig.subplots_adjust(right=0.92)\n",
    "cbar_ax = fig.add_axes([0.94, 0.15, 0.015, 0.7])\n",
    "fig.colorbar(im, cax=cbar_ax, label='Mean density')\n",
    "\n",
    "fig.suptitle('Class-Average Density Maps (visual fingerprints)', fontsize=13, y=1.01)\n",
    "fig.savefig(FIG_DIR / '11_class_mean_montage.pdf', bbox_inches='tight')\n",
    "plt.show()",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Section 12 — Sparsity & Energy
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md([
    "---\n",
    "## Section 12 — Sparsity and Energy Distribution\n",
    "\n",
    "**Left:** Violin plots of sparsity ratio (fraction of near-zero pixels)\n",
    "per shell, pooled across all classes.\n",
    "**Right:** Stacked bars showing how each class distributes total density\n",
    "mass across shells.",
]))

cells.append(code([
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5.5),\n",
    "                                gridspec_kw={'wspace': 0.35})\n",
    "\n",
    "# Left: sparsity violin plots\n",
    "sparsity_per_shell = {s: [] for s in range(N_SHELLS)}\n",
    "for cls in STAT_CLASSES:\n",
    "    sp = class_sparsity[cls]  # (N, 8)\n",
    "    for s in range(N_SHELLS):\n",
    "        sparsity_per_shell[s].extend(sp[:, s].tolist())\n",
    "\n",
    "violin_sp = [sparsity_per_shell[s] for s in range(N_SHELLS)]\n",
    "parts = ax1.violinplot(violin_sp, positions=range(1, N_SHELLS + 1),\n",
    "                       showmeans=True, showmedians=True)\n",
    "for i, pc in enumerate(parts['bodies']):\n",
    "    pc.set_facecolor(SHELL_COLORS[i])\n",
    "    pc.set_alpha(0.7)\n",
    "parts['cmeans'].set_color('red')\n",
    "parts['cmedians'].set_color('black')\n",
    "\n",
    "ax1.set_xticks(range(1, N_SHELLS + 1))\n",
    "ax1.set_xticklabels([f'S{s+1}' for s in range(N_SHELLS)])\n",
    "ax1.set_xlabel('Shell')\n",
    "ax1.set_ylabel('Sparsity ratio (fraction of near-zero pixels)')\n",
    "ax1.set_title('Per-Shell Sparsity')\n",
    "ax1.set_ylim(-0.05, 1.05)\n",
    "ax1.grid(axis='y', alpha=0.3)\n",
    "ax1.text(-0.08, 1.05, '(a)', transform=ax1.transAxes,\n",
    "         fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "# Right: stacked energy bars\n",
    "x_pos = np.arange(len(STAT_CLASSES))\n",
    "bottoms = np.zeros(len(STAT_CLASSES))\n",
    "\n",
    "for s in range(N_SHELLS):\n",
    "    fracs = [class_energy_frac[cls][:, s].mean() for cls in STAT_CLASSES]\n",
    "    ax2.bar(x_pos, fracs, bottom=bottoms, color=SHELL_COLORS[s],\n",
    "            label=f'S{s+1}', edgecolor='white', linewidth=0.5)\n",
    "    bottoms += fracs\n",
    "\n",
    "ax2.set_xticks(x_pos)\n",
    "ax2.set_xticklabels(STAT_CLASSES, rotation=45, ha='right')\n",
    "ax2.set_ylabel('Fraction of total density')\n",
    "ax2.set_title('Energy Distribution Across Shells')\n",
    "ax2.legend(fontsize=7, ncol=4, loc='upper right',\n",
    "           frameon=True, fancybox=False, edgecolor='gray')\n",
    "ax2.set_ylim(0, 1.05)\n",
    "ax2.grid(axis='y', alpha=0.3)\n",
    "ax2.text(-0.08, 1.05, '(b)', transform=ax2.transAxes,\n",
    "         fontsize=11, fontweight='bold', va='top')\n",
    "\n",
    "fig.suptitle('Sparsity and Energy Distribution', fontsize=13, y=1.02)\n",
    "fig.tight_layout()\n",
    "fig.savefig(FIG_DIR / '12_sparsity_energy.pdf', bbox_inches='tight')\n",
    "plt.show()",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Summary cell
# ═══════════════════════════════════════════════════════════════════════════════
cells.append(md(["---\n", "## All figures saved"]))

cells.append(code([
    "pdfs = sorted(FIG_DIR.glob('*.pdf'))\n",
    "print(f'{len(pdfs)} figures saved to {FIG_DIR}:')\n",
    "for p in pdfs:\n",
    "    print(f'  {p.name}')",
]))

# ═══════════════════════════════════════════════════════════════════════════════
# Build notebook JSON
# ═══════════════════════════════════════════════════════════════════════════════
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": ".venv (3.13.12)",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "cells": cells,
}

out = Path(__file__).resolve().parent.parent / "notebooks" / "erp_cache_visualization.ipynb"
with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Wrote {len(cells)} cells to {out}")
