"""Patch results_analysis.ipynb to support both MN10 and MN40 datasets."""
import json
from pathlib import Path

NB_PATH = Path(__file__).parent.parent / "notebooks" / "results_analysis.ipynb"

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

cells = nb["cells"]

# ===========================================================================
# CELL 9 — Gap analysis: add MN40 alongside MN10
# ===========================================================================
CELL9_NEW = (
    "# --- Gap analysis: how far are we from the paper's geometric ERP results? ---\n"
    "# This is TCC-critical: it quantifies the effect of using 3DGS instead of ray-casting.\n"
    "# Produces separate figures for MN10 and MN40.\n"
    "\n"
    "if not runs:\n"
    "    print('No runs available.')\n"
    "else:\n"
    "    def _plot_gap_analysis(dataset_tag: str, title_suffix: str) -> None:\n"
    "        \"\"\"Plot gap analysis bar chart for one dataset tag ('mn10' or 'mn40').\"\"\"\n"
    "        matching = [\n"
    "            (run_name, entry)\n"
    "            for run_name, entry in runs.items()\n"
    "            if dataset_tag in run_name.lower() and entry.get('test') is not None\n"
    "        ]\n"
    "        if not matching:\n"
    "            print(f'No {dataset_tag.upper()} runs found for gap analysis.')\n"
    "            return\n"
    "\n"
    "        gap_labels, gap_values, gap_colors, gap_oas, gap_targets = [], [], [], [], []\n"
    "\n"
    "        for run_name, entry in matching:\n"
    "            test   = entry['test']\n"
    "            oa     = _oa_to_pct(test.get('oa'))\n"
    "            target = _get_paper_target(run_name)\n"
    "            if target is None:\n"
    "                continue\n"
    "            gap    = target - oa\n"
    "            color, _, lbl = _run_style(run_name)\n"
    "\n"
    "            gap_labels.append(f'{lbl}\\n(target {target:.1f}% geometric ERP)')\n"
    "            gap_values.append(gap)\n"
    "            gap_colors.append(color)\n"
    "            gap_oas.append(oa)\n"
    "            gap_targets.append(target)\n"
    "\n"
    "        if not gap_labels:\n"
    "            print(f'No paper targets found for {dataset_tag.upper()} runs.')\n"
    "            return\n"
    "\n"
    "        fig2, ax2 = plt.subplots(figsize=(9, max(2.5, len(gap_labels) * 1.5)))\n"
    "        y_pos = np.arange(len(gap_labels))\n"
    "        bars  = ax2.barh(y_pos, gap_values, color=gap_colors, alpha=0.85, height=0.5)\n"
    "\n"
    "        for bar, v, oa, tgt in zip(bars, gap_values, gap_oas, gap_targets):\n"
    "            ax2.text(\n"
    "                bar.get_width() + 0.1,\n"
    "                bar.get_y() + bar.get_height() / 2,\n"
    "                f'+{v:.2f} pp  (ours: {oa:.2f}%  target: {tgt:.1f}%)',\n"
    "                va='center', fontsize=9, fontweight='bold',\n"
    "            )\n"
    "\n"
    "        ax2.axvline(0, color='black', linewidth=0.8)\n"
    "        ax2.set_yticks(y_pos)\n"
    "        ax2.set_yticklabels(gap_labels, fontsize=9)\n"
    "        ax2.set_xlabel('Performance gap vs. geometric ERP baseline (percentage points)')\n"
    "        ax2.set_title(\n"
    "            f'Performance Gap vs. Geometric ERP Baseline\\n'\n"
    "            f'3DGS Radiance Field ERP \\u2014 {title_suffix}'\n"
    "        )\n"
    "        ax2.set_xlim(0, max(gap_values) + 4)\n"
    "        ax2.grid(True, axis='x', linestyle='--', alpha=0.4)\n"
    "        ax2.spines['left'].set_visible(False)\n"
    "\n"
    "        plt.tight_layout()\n"
    "        fname = f'gap_analysis_{dataset_tag}'\n"
    "        for ext in ('png', 'pdf'):\n"
    "            fig2.savefig(\n"
    "                FIGURES_DIR / f'{fname}.{ext}',\n"
    "                dpi=300, bbox_inches='tight',\n"
    "            )\n"
    "        plt.show()\n"
    "        print(f'Saved: {FIGURES_DIR}/{fname}.*')\n"
    "\n"
    "        print(f'\\nInterpretation for TCC ({title_suffix}):')\n"
    "        for lbl, gap, oa, tgt in zip(gap_labels, gap_values, gap_oas, gap_targets):\n"
    "            lbl_clean = lbl.split('\\n')[0].strip()\n"
    "            print(f'  {lbl_clean}: {oa:.2f}% vs {tgt:.1f}% ({gap:+.2f} pp gap)')\n"
    "\n"
    "    _plot_gap_analysis('mn10', 'ModelNet10')\n"
    "    print()\n"
    "    _plot_gap_analysis('mn40', 'ModelNet40')\n"
    "\n"
    "    print()\n"
    "    print('The gap quantifies the information loss from using volumetric radiance')\n"
    "    print('field ERP (3DGS) vs. precise geometric ray-casting on raw mesh files.')\n"
)

# ===========================================================================
# CELL 16 — Combined training curves: split by dataset
# ===========================================================================
CELL16_NEW = (
    "# Combined training curves: one figure per dataset (MN10 and MN40).\n"
    "# Key TCC comparison figures showing how 3DGS RF-ERP behaves across backbones.\n"
    "\n"
    "if not runs:\n"
    "    print('No runs available.')\n"
    "else:\n"
    "    def _plot_combined_curves(dataset_tag: str, title_suffix: str, fname: str) -> None:\n"
    "        \"\"\"Plot combined val loss/acc curves for all runs matching dataset_tag.\"\"\"\n"
    "        run_data = [\n"
    "            (name, entry['metrics_df'])\n"
    "            for name, entry in runs.items()\n"
    "            if dataset_tag in name.lower() and entry.get('metrics_df') is not None\n"
    "        ]\n"
    "        if not run_data:\n"
    "            print(f'No metrics DataFrames found for {dataset_tag.upper()}.')\n"
    "            return\n"
    "\n"
    "        fig, (ax_loss, ax_acc) = plt.subplots(1, 2, figsize=(14, 5))\n"
    "        fig.suptitle(\n"
    "            f'Training Comparison \\u2014 {title_suffix}\\n'\n"
    "            '3DGS Radiance Field ERP \\u2014 EMA smoothing alpha=0.8',\n"
    "            fontsize=11, y=1.02,\n"
    "        )\n"
    "\n"
    "        for run_name, df in run_data:\n"
    "            color, ls, label = _run_style(run_name)\n"
    "            epochs = df['epoch'].values\n"
    "\n"
    "            val_loss_raw = df['val_loss'].values\n"
    "            val_acc_raw  = df['val_acc'].values\n"
    "            val_loss_s   = ema_smooth(val_loss_raw, alpha=0.8)\n"
    "            val_acc_s    = ema_smooth(val_acc_raw,  alpha=0.8)\n"
    "\n"
    "            best_idx   = int(df['val_acc'].idxmax())\n"
    "            best_epoch = int(df.loc[best_idx, 'epoch'])\n"
    "            best_val   = float(df.loc[best_idx, 'val_acc'])\n"
    "\n"
    "            # Loss panel\n"
    "            ax_loss.plot(epochs, val_loss_raw, color=color, alpha=0.18, linewidth=0.8)\n"
    "            ax_loss.plot(epochs, val_loss_s, color=color, linestyle=ls,\n"
    "                         linewidth=2.0, label=f'{label} val loss')\n"
    "            ax_loss.axvline(best_epoch, color=color, linestyle=':', linewidth=1.2, alpha=0.7)\n"
    "\n"
    "            # Accuracy panel\n"
    "            ax_acc.plot(epochs, val_acc_raw, color=color, alpha=0.18, linewidth=0.8)\n"
    "            ax_acc.plot(epochs, val_acc_s, color=color, linestyle=ls,\n"
    "                        linewidth=2.0, label=f'{label}')\n"
    "            ax_acc.plot(\n"
    "                best_epoch, best_val,\n"
    "                marker='*', markersize=13, color=color, zorder=5,\n"
    "                label=f'{label} best: {best_val:.1f}% @ ep {best_epoch}',\n"
    "            )\n"
    "\n"
    "        ax_loss.set_xlabel('Epoch')\n"
    "        ax_loss.set_ylabel('Validation Loss (cross-entropy)')\n"
    "        ax_loss.set_title('Validation Loss')\n"
    "        ax_loss.legend(loc='upper right', fontsize=8)\n"
    "\n"
    "        ax_acc.set_xlabel('Epoch')\n"
    "        ax_acc.set_ylabel('Validation Accuracy (%)')\n"
    "        ax_acc.set_title('Validation Accuracy')\n"
    "        ax_acc.legend(loc='lower right', fontsize=8)\n"
    "\n"
    "        plt.tight_layout()\n"
    "        for ext in ('png', 'pdf'):\n"
    "            fig.savefig(\n"
    "                FIGURES_DIR / f'{fname}.{ext}',\n"
    "                dpi=300, bbox_inches='tight',\n"
    "            )\n"
    "        plt.show()\n"
    "        print(f'Saved: {FIGURES_DIR}/{fname}.*')\n"
    "\n"
    "    _plot_combined_curves('mn10', 'ModelNet10', 'training_curves_mn10_combined')\n"
    "    print()\n"
    "    _plot_combined_curves('mn40', 'ModelNet40', 'training_curves_mn40_combined')\n"
)

# ===========================================================================
# CELL 22 — Convergence thresholds: split by dataset
# ===========================================================================
CELL22_NEW = (
    "# For each run: first epoch at which val_acc crosses each threshold.\n"
    "# Shows convergence speed -- important for practical deployment discussions.\n"
    "# Produces separate charts for MN10 and MN40.\n"
    "\n"
    "if not runs:\n"
    "    print('No runs available.')\n"
    "else:\n"
    "    def _plot_convergence(dataset_tag: str, title_suffix: str, fname: str) -> None:\n"
    "        \"\"\"Plot convergence threshold chart for runs matching dataset_tag.\"\"\"\n"
    "        thresholds = [70, 80, 85, 90, 92, 94, 95]\n"
    "        convergence_data = {}   # label -> (run_name, {threshold -> epoch | None})\n"
    "\n"
    "        for run_name, entry in runs.items():\n"
    "            if dataset_tag not in run_name.lower():\n"
    "                continue\n"
    "            df = entry.get('metrics_df')\n"
    "            if df is None:\n"
    "                continue\n"
    "            _, _, label = _run_style(run_name)\n"
    "            thr_eps = {}\n"
    "            for thr in thresholds:\n"
    "                mask = df['val_acc'] >= thr\n"
    "                if mask.any():\n"
    "                    first_idx = int(mask.idxmax())\n"
    "                    thr_eps[thr] = int(df.loc[first_idx, 'epoch'])\n"
    "                else:\n"
    "                    thr_eps[thr] = None\n"
    "            convergence_data[label] = (run_name, thr_eps)\n"
    "\n"
    "        if not convergence_data:\n"
    "            print(f'No convergence data available for {dataset_tag.upper()}.')\n"
    "            return\n"
    "\n"
    "        # Print table\n"
    "        print(f'Epochs to first reach each val accuracy threshold ({title_suffix}):\\n')\n"
    "        thr_df_rows = []\n"
    "        for label, (_, thr_ep) in convergence_data.items():\n"
    "            row = {'Model': label}\n"
    "            for thr in thresholds:\n"
    "                ep = thr_ep.get(thr)\n"
    "                row[f'>={thr}%'] = ep if ep is not None else 'N/A'\n"
    "            thr_df_rows.append(row)\n"
    "        thr_df = pd.DataFrame(thr_df_rows).set_index('Model')\n"
    "        display(thr_df)\n"
    "\n"
    "        # Bar chart\n"
    "        n_models = len(convergence_data)\n"
    "        n_thrs   = len(thresholds)\n"
    "        bar_h    = 0.35\n"
    "        x_pos    = np.arange(n_thrs)\n"
    "        offsets  = np.linspace(\n"
    "            -(n_models - 1) * bar_h / 2,\n"
    "             (n_models - 1) * bar_h / 2,\n"
    "            n_models,\n"
    "        )\n"
    "\n"
    "        fig, ax = plt.subplots(figsize=(12, max(3.5, n_models * 1.5)))\n"
    "\n"
    "        for idx, (label, (run_name, thr_ep)) in enumerate(convergence_data.items()):\n"
    "            color, _, _ = _run_style(run_name)\n"
    "            for xi, thr in enumerate(thresholds):\n"
    "                ep = thr_ep.get(thr)\n"
    "                if ep is not None:\n"
    "                    ax.bar(\n"
    "                        xi + offsets[idx], ep, width=bar_h * 0.88,\n"
    "                        color=color, alpha=0.85,\n"
    "                        label=label if xi == 0 else None,\n"
    "                    )\n"
    "                    ax.text(\n"
    "                        xi + offsets[idx], ep + 1,\n"
    "                        str(ep), ha='center', va='bottom', fontsize=7.5,\n"
    "                    )\n"
    "                else:\n"
    "                    ax.bar(\n"
    "                        xi + offsets[idx], 3, width=bar_h * 0.88,\n"
    "                        color='none', edgecolor=color, linestyle='--', linewidth=1.2,\n"
    "                    )\n"
    "                    ax.text(\n"
    "                        xi + offsets[idx], 5, 'N/A',\n"
    "                        ha='center', va='bottom', fontsize=7, color=color,\n"
    "                    )\n"
    "\n"
    "        ax.set_xticks(x_pos)\n"
    "        ax.set_xticklabels([f'>={t}%' for t in thresholds], fontsize=9)\n"
    "        ax.set_xlabel('Validation accuracy threshold')\n"
    "        ax.set_ylabel('First epoch reaching threshold')\n"
    "        ax.set_title(\n"
    "            f'Convergence: Epochs to Reach Accuracy Thresholds\\n{title_suffix} \\u2014 3DGS Radiance Field ERP'\n"
    "        )\n"
    "        ax.legend(loc='upper left', fontsize=9)\n"
    "        ax.grid(True, axis='y', linestyle='--', alpha=0.35)\n"
    "\n"
    "        plt.tight_layout()\n"
    "        for ext in ('png', 'pdf'):\n"
    "            fig.savefig(\n"
    "                FIGURES_DIR / f'{fname}.{ext}',\n"
    "                dpi=300, bbox_inches='tight',\n"
    "            )\n"
    "        plt.show()\n"
    "        print(f'Saved: {FIGURES_DIR}/{fname}.*')\n"
    "\n"
    "    _plot_convergence('mn10', 'ModelNet10', 'convergence_thresholds_mn10')\n"
    "    print()\n"
    "    _plot_convergence('mn40', 'ModelNet40', 'convergence_thresholds_mn40')\n"
)

# ===========================================================================
# CELL 28 — Per-class comparison: MN10 grouped vs MN40 single-model
# ===========================================================================
CELL28_NEW = (
    "# Per-class accuracy charts, split by dataset.\n"
    "# MN10: grouped horizontal bar chart comparing 2 models side-by-side.\n"
    "# MN40: single-model horizontal bar chart (one MN40 run completed;\n"
    "#        falls back to a grouped chart if multiple MN40 runs exist).\n"
    "\n"
    "if not runs:\n"
    "    print('No runs available.')\n"
    "else:\n"
    "    # Collect per-class data keyed by dataset\n"
    "    mn10_results = {}   # label -> (per_class_array, class_names, run_name)\n"
    "    mn40_results = {}\n"
    "\n"
    "    for run_name, entry in runs.items():\n"
    "        y_true = entry.get('y_true')\n"
    "        y_pred = entry.get('y_pred')\n"
    "        if y_true is None or y_pred is None:\n"
    "            continue\n"
    "        test        = entry.get('test') or {}\n"
    "        n_cls       = int(test.get('num_classes', int(y_true.max()) + 1))\n"
    "        class_names = class_names_for(n_cls)\n"
    "        per_class   = compute_per_class_accuracy(y_true, y_pred, n_cls)\n"
    "        _, _, label = _run_style(run_name)\n"
    "\n"
    "        if 'mn10' in run_name.lower():\n"
    "            mn10_results[label] = (per_class, class_names, run_name)\n"
    "        elif 'mn40' in run_name.lower():\n"
    "            mn40_results[label] = (per_class, class_names, run_name)\n"
    "\n"
    "    # --- MN10: grouped comparison (2+ models) or single-model bar chart ---\n"
    "    if len(mn10_results) >= 2:\n"
    "        ref_label = next(iter(mn10_results))\n"
    "        _, class_names, _ = mn10_results[ref_label]\n"
    "        n_cls = len(class_names)\n"
    "\n"
    "        labels_list = list(mn10_results.keys())\n"
    "        n_models    = len(labels_list)\n"
    "        bar_h       = 0.72 / n_models\n"
    "        y_pos       = np.arange(n_cls)\n"
    "        offsets     = np.linspace(\n"
    "            -(n_models - 1) * bar_h / 2,\n"
    "             (n_models - 1) * bar_h / 2,\n"
    "            n_models,\n"
    "        )\n"
    "\n"
    "        fig, ax = plt.subplots(figsize=(11, max(5, n_cls * 0.60)))\n"
    "\n"
    "        for idx, (label, (per_class, _, run_name)) in enumerate(mn10_results.items()):\n"
    "            color = COLORS['hsdc'] if 'HSDC' in label else COLORS['swhdc']\n"
    "            pct   = per_class * 100\n"
    "            bars  = ax.barh(\n"
    "                y_pos + offsets[idx], pct,\n"
    "                height=bar_h * 0.88,\n"
    "                color=color, alpha=0.82,\n"
    "                label=label,\n"
    "            )\n"
    "            for bar, v in zip(bars, pct):\n"
    "                ax.text(\n"
    "                    bar.get_width() + 0.5,\n"
    "                    bar.get_y() + bar.get_height() / 2,\n"
    "                    f'{v:.0f}%',\n"
    "                    va='center', fontsize=7.5, color=color,\n"
    "                )\n"
    "\n"
    "        for label, (per_class, _, _) in mn10_results.items():\n"
    "            color    = COLORS['hsdc'] if 'HSDC' in label else COLORS['swhdc']\n"
    "            mean_acc = per_class.mean() * 100\n"
    "            ax.axvline(mean_acc, color=color, linestyle='--', linewidth=1.2, alpha=0.7,\n"
    "                       label=f'{label} mean: {mean_acc:.1f}%')\n"
    "\n"
    "        ax.set_yticks(y_pos)\n"
    "        ax.set_yticklabels(class_names, fontsize=9)\n"
    "        ax.set_xlabel('Per-class Accuracy (%)')\n"
    "        ax.set_title(\n"
    "            'Per-class Accuracy Comparison \\u2014 ModelNet10\\n'\n"
    "            '3DGS Radiance Field ERP'\n"
    "        )\n"
    "        ax.set_xlim(0, 110)\n"
    "        ax.legend(loc='lower right', fontsize=8)\n"
    "        ax.grid(True, axis='x', linestyle='--', alpha=0.35)\n"
    "        ax.invert_yaxis()\n"
    "\n"
    "        plt.tight_layout()\n"
    "        for ext in ('png', 'pdf'):\n"
    "            fig.savefig(\n"
    "                FIGURES_DIR / f'per_class_comparison_mn10.{ext}',\n"
    "                dpi=300, bbox_inches='tight',\n"
    "            )\n"
    "        plt.show()\n"
    "        print(f'Saved: {FIGURES_DIR}/per_class_comparison_mn10.*')\n"
    "\n"
    "        items = list(mn10_results.items())\n"
    "        if len(items) >= 2:\n"
    "            lbl_a, (pc_a, cls_names, _) = items[0]\n"
    "            lbl_b, (pc_b, _, _)         = items[1]\n"
    "            diff = (pc_a - pc_b) * 100\n"
    "            print(f'\\nClass-level comparison ({lbl_a} - {lbl_b}):')\n"
    "            for cls, d in sorted(zip(cls_names, diff), key=lambda x: -abs(x[1])):\n"
    "                winner = lbl_a if d > 0 else (lbl_b if d < 0 else 'tie')\n"
    "                print(f'  {cls:15s}: {d:+.1f} pp  -> {winner} wins')\n"
    "\n"
    "    elif len(mn10_results) == 1:\n"
    "        label, (per_class, class_names, _) = next(iter(mn10_results.items()))\n"
    "        fig = plot_per_class_accuracy(\n"
    "            per_class, class_names, run_label=label,\n"
    "            save_path=FIGURES_DIR / 'per_class_comparison_mn10',\n"
    "        )\n"
    "        plt.show()\n"
    "        print(f'Saved: {FIGURES_DIR}/per_class_comparison_mn10.*')\n"
    "    else:\n"
    "        print('No MN10 runs with predictions found.')\n"
    "\n"
    "    print()\n"
    "\n"
    "    # --- MN40: single-model bar chart; grouped if multiple MN40 runs ---\n"
    "    if len(mn40_results) == 1:\n"
    "        label, (per_class, class_names, _) = next(iter(mn40_results.items()))\n"
    "        fig = plot_per_class_accuracy(\n"
    "            per_class, class_names, run_label=f'{label} (ModelNet40)',\n"
    "            save_path=FIGURES_DIR / 'per_class_accuracy_mn40',\n"
    "        )\n"
    "        plt.show()\n"
    "        print(f'Saved: {FIGURES_DIR}/per_class_accuracy_mn40.*')\n"
    "\n"
    "    elif len(mn40_results) >= 2:\n"
    "        ref_label = next(iter(mn40_results))\n"
    "        _, class_names_40, _ = mn40_results[ref_label]\n"
    "        n_cls40 = len(class_names_40)\n"
    "\n"
    "        labels_40  = list(mn40_results.keys())\n"
    "        n_models40 = len(labels_40)\n"
    "        bar_h40    = 0.72 / n_models40\n"
    "        y_pos40    = np.arange(n_cls40)\n"
    "        offsets40  = np.linspace(\n"
    "            -(n_models40 - 1) * bar_h40 / 2,\n"
    "             (n_models40 - 1) * bar_h40 / 2,\n"
    "            n_models40,\n"
    "        )\n"
    "\n"
    "        fig40, ax40 = plt.subplots(figsize=(11, max(8, n_cls40 * 0.45)))\n"
    "        for idx, (lbl, (pc, _, run_name)) in enumerate(mn40_results.items()):\n"
    "            color = COLORS['hsdc'] if 'HSDC' in lbl else COLORS['swhdc']\n"
    "            pct   = pc * 100\n"
    "            ax40.barh(\n"
    "                y_pos40 + offsets40[idx], pct,\n"
    "                height=bar_h40 * 0.88,\n"
    "                color=color, alpha=0.82, label=lbl,\n"
    "            )\n"
    "        ax40.set_yticks(y_pos40)\n"
    "        ax40.set_yticklabels(class_names_40, fontsize=7)\n"
    "        ax40.set_xlabel('Per-class Accuracy (%)')\n"
    "        ax40.set_title(\n"
    "            'Per-class Accuracy Comparison \\u2014 ModelNet40\\n'\n"
    "            '3DGS Radiance Field ERP'\n"
    "        )\n"
    "        ax40.set_xlim(0, 110)\n"
    "        ax40.legend(loc='lower right', fontsize=8)\n"
    "        ax40.grid(True, axis='x', linestyle='--', alpha=0.35)\n"
    "        ax40.invert_yaxis()\n"
    "        plt.tight_layout()\n"
    "        for ext in ('png', 'pdf'):\n"
    "            fig40.savefig(\n"
    "                FIGURES_DIR / f'per_class_comparison_mn40.{ext}',\n"
    "                dpi=300, bbox_inches='tight',\n"
    "            )\n"
    "        plt.show()\n"
    "        print(f'Saved: {FIGURES_DIR}/per_class_comparison_mn40.*')\n"
    "    else:\n"
    "        print('No MN40 runs with predictions found.')\n"
)

# ===========================================================================
# CELL 30 — Pareto plot: MN10 + new MN40 plot
# ===========================================================================
CELL30_NEW = (
    "# Auto-populate proposed dicts from completed runs, then draw Pareto plots\n"
    "# for MN10 and MN40 separately.\n"
    "# Shows where 3DGS RF-ERP sits relative to each dataset's literature landscape.\n"
    "\n"
    "proposed_mn10 = {}\n"
    "proposed_mn40 = {}\n"
    "\n"
    "for run_name, entry in runs.items():\n"
    "    test = entry.get('test')\n"
    "    if test is None:\n"
    "        continue\n"
    "    oa     = _oa_to_pct(test.get('oa'))\n"
    "    params = test.get('params_m', float('nan'))\n"
    "    _, _, label = _run_style(run_name)\n"
    "    point = (params, oa)\n"
    "\n"
    "    if 'mn10' in run_name.lower():\n"
    "        proposed_mn10[f'{label}\\n(RF-ERP)'] = point\n"
    "    elif 'mn40' in run_name.lower():\n"
    "        proposed_mn40[f'{label}\\n(RF-ERP)'] = point\n"
    "\n"
    "# --- MN10 Pareto ---\n"
    "fig_mn10 = plot_pareto(\n"
    "    proposed=proposed_mn10,\n"
    "    dataset='MN10',\n"
    "    title='Parameter-Accuracy Trade-off on ModelNet10\\n3DGS Radiance Field ERP vs. Literature',\n"
    "    save_path=FIGURES_DIR / 'pareto_mn10',\n"
    ")\n"
    "plt.show()\n"
    "print(f'Saved: {FIGURES_DIR}/pareto_mn10.*')\n"
    "\n"
    "if proposed_mn10:\n"
    "    print('\\nProposed methods \\u2014 MN10 (this work):')\n"
    "    for lbl, (p, a) in proposed_mn10.items():\n"
    "        print(f'  {lbl.replace(chr(10), \" \")}: {p:.2f}M params, {a:.2f}% OA')\n"
    "else:\n"
    "    print('No MN10 runs found \\u2014 Pareto shows literature only.')\n"
    "\n"
    "print()\n"
    "\n"
    "# --- MN40 Pareto ---\n"
    "fig_mn40 = plot_pareto(\n"
    "    proposed=proposed_mn40,\n"
    "    dataset='MN40',\n"
    "    title='Parameter-Accuracy Trade-off on ModelNet40\\n3DGS Radiance Field ERP vs. Literature',\n"
    "    save_path=FIGURES_DIR / 'pareto_mn40',\n"
    ")\n"
    "plt.show()\n"
    "print(f'Saved: {FIGURES_DIR}/pareto_mn40.*')\n"
    "\n"
    "if proposed_mn40:\n"
    "    print('\\nProposed methods \\u2014 MN40 (this work):')\n"
    "    for lbl, (p, a) in proposed_mn40.items():\n"
    "        print(f'  {lbl.replace(chr(10), \" \")}: {p:.2f}M params, {a:.2f}% OA')\n"
    "else:\n"
    "    print('No MN40 runs found \\u2014 Pareto shows literature only.')\n"
)

# Apply all changes
cells[9]['source']  = [CELL9_NEW]
cells[16]['source'] = [CELL16_NEW]
cells[22]['source'] = [CELL22_NEW]
cells[28]['source'] = [CELL28_NEW]
cells[30]['source'] = [CELL30_NEW]

# Write back
with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Notebook patched successfully: {NB_PATH}")
print(f"Total cells: {len(nb['cells'])}")
